"use client";

import { useEffect, useState } from "react";
import { AlertTriangle, Check, X } from "lucide-react";
import Sidebar from "@/components/Sidebar";
import DonutChart from "@/components/DonutChart";
import { getRecommendations, dismissRecommendation, type Recommendation } from "@/lib/api";
import { useAuth } from "@/lib/auth/AuthContext";


export default function InsightsPage() {
  const { user } = useAuth();
  const USER_ID = user?.userId;
  const [recommendations, setRecommendations] = useState<Recommendation[]>([]);
  const [loading, setLoading] = useState(true);
  const [dismissedCount, setDismissedCount] = useState(0);

  async function load() {
    if (!USER_ID) return;
    try {
      const data = await getRecommendations(USER_ID);
      setRecommendations(data);
    } catch {
      // Spring Boot / Python not reachable — page still renders empty
    } finally {
      setLoading(false);
    }
  }

  useEffect(() => {
    load();
  }, [USER_ID]);

  async function handleDismiss(id: number) {
    await dismissRecommendation(id);
    setDismissedCount((c) => c + 1);
    await load();
  }

  return (
    <div className="flex flex-col md:flex-row min-h-screen bg-[#F4F6F8] dark:bg-slate-900">
      <Sidebar />
      <main className="flex-1 px-4 py-6 md:px-10 md:py-8 max-w-[1600px] w-full">
        <h1 className="text-4xl font-bold text-slate-900 dark:text-white mb-1">Smart Insights</h1>
        <p className="text-slate-500 dark:text-slate-400 mb-8">
          Data-driven recommendations to optimize your energy usage.
        </p>

        <div className="flex gap-6 flex-wrap items-start">
          <div className="flex-[2] min-w-full md:min-w-[420px]">
            <h2 className="text-2xl font-bold text-slate-900 dark:text-white mb-4">Top Recommendations</h2>

            {loading ? (
              <div className="flex flex-col gap-4">
                {[1, 2].map((i) => (
                  <div key={i} className="h-28 rounded-2xl bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700 animate-pulse" />
                ))}
              </div>
            ) : recommendations.length === 0 ? (
              <div className="bg-white dark:bg-slate-800 rounded-2xl border border-slate-200 dark:border-slate-700 p-8 text-center">
                <p className="text-slate-500 dark:text-slate-400">
                  No recommendations yet. Log a few appliance readings on the Consumption page —
                  once your usage patterns are analyzed, personalized tips will appear here.
                </p>
              </div>
            ) : (
              <div className="flex flex-col gap-4">
                {recommendations.map((r) => (
                  <div
                    key={r.recommendationId}
                    className="bg-white dark:bg-slate-800 rounded-2xl border border-slate-200 dark:border-slate-700 p-6 flex items-start gap-4"
                  >
                    <div className="w-12 h-12 rounded-xl bg-amber-100 flex items-center justify-center shrink-0">
                      <AlertTriangle className="w-5 h-5 text-amber-600" />
                    </div>
                    <div className="flex-1">
                      <h3 className="font-bold text-slate-900 dark:text-white mb-1 capitalize">
                        {r.recommendationType.replace(/_/g, " ")}
                      </h3>
                      <p className="text-sm text-slate-600">{r.message}</p>
                    </div>
                    <button
                      onClick={() => handleDismiss(r.recommendationId)}
                      className="flex items-center gap-1.5 bg-slate-100 hover:bg-slate-200 transition-colors text-slate-700 dark:text-slate-300 text-sm font-semibold px-4 py-2 rounded-xl shrink-0"
                    >
                      <Check className="w-4 h-4" /> Dismiss
                    </button>
                  </div>
                ))}
              </div>
            )}
          </div>

          <div className="flex flex-col gap-6 flex-1 min-w-full md:min-w-[280px]">
            <section className="bg-white dark:bg-slate-800 rounded-2xl border border-slate-200 dark:border-slate-700 p-6">
              <h2 className="text-xl font-bold text-slate-900 dark:text-white mb-4 text-center">Active Recommendations</h2>
              <DonutChart
                data={[
                  { name: "Open", value: recommendations.length || 1, color: "#2563EB" },
                  { name: "Resolved", value: dismissedCount || 0.001, color: "#E2E8F0" },
                ]}
                centerValue={String(recommendations.length)}
                centerLabel="open"
              />
              <p className="text-sm text-slate-500 dark:text-slate-400 text-center mt-2">
                Generated by your usage-pattern analysis.
              </p>
            </section>

            <section className="bg-white dark:bg-slate-800 rounded-2xl border border-slate-200 dark:border-slate-700 p-6">
              <h2 className="text-xl font-bold text-slate-900 dark:text-white mb-4">Dismissed This Session</h2>
              {dismissedCount === 0 ? (
                <p className="text-sm text-slate-500 dark:text-slate-400">Nothing dismissed yet.</p>
              ) : (
                <div className="flex items-start gap-3">
                  <div className="w-7 h-7 rounded-full bg-emerald-100 flex items-center justify-center shrink-0">
                    <Check className="w-3.5 h-3.5 text-emerald-600" />
                  </div>
                  <p className="text-sm text-slate-600">
                    {dismissedCount} recommendation{dismissedCount > 1 ? "s" : ""} handled.
                  </p>
                </div>
              )}
            </section>
          </div>
        </div>
      </main>
    </div>
  );
}
